const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {chromium}=require(process.env.MTYPE_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.MTYPE_BROWSER_PATH});
 const page=await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:4173/template/index.html');
 await page.locator('#characterImage').evaluate(img=>img.decode());
 assert.equal(await page.locator('.type-code').textContent(),'CSNL');
 assert.equal(await page.locator('.stat').count(),3);
 await page.screenshot({path:path.join(root,'output/desktop-preview.png'),fullPage:true});
 await page.locator('#report').screenshot({path:path.join(root,'output/report-desktop.png')});
 const desktopPNG=await page.evaluate(()=>MTypeApp.exportReport(false));fs.writeFileSync(path.join(root,'output/M-TYPE-演示档案.png'),Buffer.from(desktopPNG.split(',')[1],'base64'));
 await page.getByRole('button',{name:'16 型人格',exact:true}).click();
 assert.equal(await page.locator('.gallery-card').count(),16);
 await page.locator('.gallery-card img').evaluateAll(async imgs=>{for(const img of imgs){img.loading='eager';await img.decode();}});
 await page.locator('#gallery').evaluate(dialog=>{dialog.style.maxHeight='none';dialog.style.position='absolute';dialog.style.top='0';dialog.style.bottom='auto';dialog.style.margin='0 auto';});
 await page.locator('#gallery').screenshot({path:path.join(root,'output/16-personalities.png')});
 await page.locator('#gallery').evaluate(dialog=>dialog.removeAttribute('style'));
 await page.getByRole('button',{name:'关闭人格图鉴'}).click();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'手机端横向溢出');
 await page.screenshot({path:path.join(root,'output/mobile-preview.png'),fullPage:true});
 const png=await page.evaluate(()=>MTypeApp.exportReport(false));
 fs.writeFileSync(path.join(root,'output/M-TYPE-手机长图.png'),Buffer.from(png.split(',')[1],'base64'));
 await page.locator('#showAmount').check();assert.equal(await page.locator('.stat').count(),4);
 await page.locator('#resetDemo').click();
 const unsafe={orders:Array.from({length:5},(_,i)=>({id:String(i),status:'completed',orderedAt:`2026-09-0${i+1}T12:30:00+08:00`,discountAmount:0,items:[{productName:'<img src=x onerror=alert(1)>',quantity:1,tags:['classic']}]}))};
 await page.evaluate(data=>MTypeApp.loadData(data),unsafe);
 assert.equal(await page.locator('#report [onerror]').count(),0,'导入内容未转义');assert.equal(await page.locator('#report .character').count(),1);assert.equal(await page.locator('#showAmount').isDisabled(),true);
 await page.evaluate(()=>MTypeApp.loadData({orders:[]}));assert.equal(await page.locator('#questions fieldset').count(),4);assert.equal(await page.locator('#exportButton').isDisabled(),true);
 await page.evaluate(()=>MTypeApp.loadData({orders:[]},{0:'E',1:'F',2:'N',3:'V'}));assert.equal(await page.locator('.type-code').textContent(),'EFNV');assert.equal(await page.locator('.moment').count(),0);
 await page.goto('file://'+path.join(root,'output/M-TYPE-麦门人格档案.html'));await page.locator('#characterImage').evaluate(img=>img.decode());
 assert.equal(await page.locator('.type-code').textContent(),'CSNL');
 assert.equal(await page.locator('#characterImage').getAttribute('src').then(src=>src.startsWith('data:image/png;base64,')),true);
 const offlinePNG=await page.evaluate(()=>MTypeApp.exportReport(false));assert.equal(offlinePNG.startsWith('data:image/png;base64,'),true);
 await page.setViewportSize({width:320,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'320px 手机端溢出');
 assert.deepEqual(errors,[]);
 console.log('PASS: desktop / 390px & 320px mobile / 16 assets / PNG export / money privacy / escaped imported content / missing records / offline HTML & export');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
